/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "evolocity.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ConfigRequest, ConfigRequest, AUTO)


PB_BIND(ConfigResponse, ConfigResponse, AUTO)


PB_BIND(EnergyFrame, EnergyFrame, AUTO)


PB_BIND(TimestampPair, TimestampPair, AUTO)


PB_BIND(EnergyRequest, EnergyRequest, AUTO)


PB_BIND(EnergyResponse, EnergyResponse, AUTO)






